# -*- coding: utf-8 -*-
"""Assignment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XzCgCiJ2G70ZDnTvLGAzGOzm7dVoWX6t
"""

import urllib.request as ul
from bs4 import BeautifulSoup as soup

# Accesing the url
url = 'https://earthdata.nasa.gov/search?q=india'
req = ul.Request(url, headers={'User-Agent': 'Chrome/87.0.4280.141'})
client = ul.urlopen(req)
htmldata = client.read()
client.close()

# Accessing the data
pagesoup = soup(htmldata, "html.parser")
itemlocator = pagesoup.findAll('section', {"class":"pages"})

filename = "news.csv"
f = open(filename, "w", encoding="utf-8")
headers = "News\n"
f.write(headers)

# Adding the data to news.csv

for items in itemlocator:   
    newscontainer = items.findAll("li",{"class":"result"})
    for i in range(0,len(newscontainer)):
         news = newscontainer[i].text
         print(news)   
         f.write(news.replace(",", " "))

f.close()